- name: Deploy React App with Nginx
  hosts: app
  become: yes

  tasks:
    - name: Update server
      apt:
        update_cache: yes

    - name: Install required packages
      apt:
        name:
          - nodejs
          - npm
          - nginx
          - git
        state: present

    - name: Clone application repository
      git:
        repo: https://github.com/GOWTHAMI9999/awesome-compose.git
        dest: /var/www/app
        force: yes

    - name: Install frontend dependencies
      npm:
        path: /var/www/app/react-nginx/frontend

    - name: Build frontend
      command: npm run build
      args:
        chdir: /var/www/app/react-nginx/frontend

    - name: Remove default nginx html
      file:
        path: /var/www/html
        state: absent

    - name: Create nginx html directory
      file:
        path: /var/www/html
        state: directory
        owner: www-data
        group: www-data
        mode: '0755'

    - name: Copy build to nginx
      copy:
        src: /var/www/app/react-nginx/frontend/build/
        dest: /var/www/html/
        remote_src: yes

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
