- name: Deploy Express app with PM2, Redis and Nginx
  hosts: managed_node
  become: yes

  vars:
    repo_root: /home/ubuntu/awesome-compose
    app_dir: /home/ubuntu/awesome-compose/nginx-nodejs-redis
    web_dir: /home/ubuntu/awesome-compose/nginx-nodejs-redis/web
    node_version: "18.x"
    app_port: 5000
    pm2_app_name: web-app

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install base packages
      apt:
        name:
          - curl
          - git
          - nginx
          - redis-server
        state: present

    - name: Install Node.js from NodeSource
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_{{ node_version }} | bash -
        apt-get install -y nodejs
      args:
        creates: /usr/bin/node

    # - name: Update application repository
    #   git:
    #     repo: https://github.com/GOWTHAMI9999/awesome-compose.git
    #     dest: "{{ repo_root }}"
    #     update: yes
    #     force: yes


    - name: Install backend dependencies
      become: false
      shell: npm install --omit=dev
      args:
        chdir: /home/ubuntu/awesome-compose/nginx-nodejs-redis/web





    - name: Install pm2 globally
      npm:
        name: pm2
        global: yes

    - name: Start application with pm2
      become_user: ubuntu
      shell: |
        cd {{ web_dir }}
        pm2 start server.js --name web-app
      ignore_errors: yes


    - name: Save pm2 process list
      become_user: ubuntu
      command: pm2 save


    - name: Enable pm2 startup on reboot
      command: pm2 startup systemd -u ubuntu --hp /home/ubuntu


    - name: Remove default nginx site
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
