- name: Deploy Express app with pm2, Redis and Nginx
  hosts: managed_node
  become: yes

  vars:
    app_root: /var/www/app
    app_dir: /home/ubuntu/awesome-compose/nginx-nodejs-redis
    node_version: "18.x"
    app_port: 5000
    pm2_app_name: express-app

  tasks:

    - name: Update apt cache
      apt:
        update_cache: yes

    - name: Install base packages
      apt:
        name:
          - curl
          - git
          - nginx
          - redis-server
        state: present

    - name: Install Node.js LTS from NodeSource
      shell: |
        curl -fsSL https://deb.nodesource.com/setup_{{ node_version }} | bash -
        apt-get install -y nodejs
      args:
        creates: /usr/bin/node

    - name: Ensure app root directory exists
      file:
        path: "{{ app_root }}"
        state: directory
        mode: "0755"

    - name: Clone application repository
      git:
        repo: https://github.com/GOWTHAMI9999/awesome-compose.git
        dest: "{{ app_root }}"
        force: yes

    - name: Install backend dependencies
      npm:
        path: "{{ app_dir }}"
        production: yes

    - name: Install pm2 globally
      npm:
        name: pm2
        global: yes

   
    - name: Start application with pm2
      command: pm2 start server.js --name web-app
      args:
      chdir: "{{ app_dir }}/web"
      ignore_errors: yes


    - name: Save pm2 process list
      command: pm2 save

    - name: Enable pm2 startup on reboot
      command: pm2 startup systemd -u {{ ansible_user_id }} --hp /home/{{ ansible_user_id }}


    # - name: Create nginx reverse proxy config
    #   copy:
    #     dest: /etc/nginx/sites-available/express-app
    #     content: |
    #       server {
    #           listen 80;
    #           server_name _;

    #           location / {
    #               proxy_pass http://127.0.0.1:{{ app_port }};
    #               proxy_http_version 1.1;
    #               proxy_set_header Upgrade $http_upgrade;
    #               proxy_set_header Connection 'upgrade';
    #               proxy_set_header Host $host;
    #               proxy_cache_bypass $http_upgrade;
    #           }
    #       }

    # - name: Enable nginx site
    #   file:
    #     src: /etc/nginx/sites-available/express-app
    #     dest: /etc/nginx/sites-enabled/express-app
    #     state: link
    #     force: yes

    - name: Remove default nginx config
      file:
        path: /etc/nginx/sites-enabled/default
        state: absent

    - name: Restart nginx
      service:
        name: nginx
        state: restarted
        enabled: yes
